#!/usr/bin/env bash
# Scrapes DNS information for a specific domain and subdomain

# Function to query and display DNS info
check_subdomain() {
    domain=$1
    sub=$2
    ip=$(dig +short "$sub.$domain" | head -n 1)
    record_type="A"
    
    if [ -n "$ip" ]; then
        echo "The subdomain $sub is a $record_type record and points to $ip"
    fi
}

# Main logic
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

DOMAIN=$1
SUBDOMAIN=$2

if [ -n "$SUBDOMAIN" ]; then
    check_subdomain "$DOMAIN" "$SUBDOMAIN"
else
    check_subdomain "$DOMAIN" "www"
    check_subdomain "$DOMAIN" "lb-01"
    check_subdomain "$DOMAIN" "web-01"
    check_subdomain "$DOMAIN" "web-02"
fi
